services:
  aspnet-app:
    build: .
    container_name: aspnet-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3307
    networks:
      - project-net
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    command: --port=3307  # Esto es importante!
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3307"  # Puerto mapeado correctamente
    networks:
      - project-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-P", "3307", "-u", "root", "-prootpassword"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  project-net:
    driver: bridge

volumes:
  mysql-data: